spring:
  application:
    name: HuskerBot2

  datasource:
    url: jdbc:h2:file:~/.discordbot/data
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

discord:
  token: ${DISCORD-TOKEN:}

  guilds:
    - 1407527947761488085 # Husker Bot Test Discord
    - 440632686185414677 # Huskers Main Discord

  categories:
    general: 1407527948713590885
    gameday: 1407782503405846629

  channels:
    possum: 1407821663336267869
    general: 1407527948713590887
    recruiting: 1407823800824889445
    admin: 1407823859155206224
    nfl-pickem: 1408123966438244403
    announcements: 1407527948713590887 #1407823859155206225

weather:
  nominatim:
    base-url: "https://nominatim.openstreetmap.org"
    rate-limit-delay: 1000
  nws:
    base-url: "https://api.weather.gov"
    user-agent: "HuskerBot2 (huskerbot@example.com)"
  tomorrow:
    base-url: "https://api.tomorrow.io/v4"
    api-key: ""
  cache:
    coordinates-ttl: 86400
    forecast-ttl: 3600

cfbd:
  base-url: "https://api.collegefootballdata.com"
  user-agent: "HuskerBot2 (huskerbot@example.com)"
  api-key: ${CFBD-KEY:}
  cache:
    matchup-ttl: 3600

urban:
  base-url: "https://api.urbandictionary.com"
  user-agent: "HuskerBot2 (huskerbot@example.com)"

backup:
  sql:
    dir: build/backups-sql

gemini:
  base-url: "https://generativelanguage.googleapis.com"
  model: "models/gemini-2.5-flash"
  api-key: ${GEMINI-KEY:}

---
# Activate this block by setting SPRING_PROFILES_ACTIVE=mysql
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:huskers}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
